export enum Event {
  ERROR_BOUNDARY = 'ERROR_BOUNDARY',
  NO_CONTROLLER_FOUND = 'NO_CONTROLLER_FOUND',
  NO_CONTROLLER_ROUTE_FOUND = 'NO_CONTROLLER_ROUTE_FOUND',
  CONTROLLER_NOT_INITIALIZED = 'CONTROLLER_NOT_INITIALIZED',
  REACT_ROUTE_RENDER = 'REACT_ROUTE_RENDER',
  APPLICATION_STARTUP = 'APPLICATION_STARTUP',
  RENDERER_METHOD = 'RENDERER_METHOD',
  SERVICE_WORKER_INIT_SUCCESS = 'SERVICE_WORKER_INIT_SUCCESS',
  SERVICE_WORKER_INIT_FAILURE = 'SERVICE_WORKER_INIT_FAILURE',
}
