/**
 * This module will be generated by webpack during the build phase. The generated
 * module constructs an import statement that imports the global css/scss file in
 * the host application. The imported file can be configued via the "cssGlobalFile"
 * configuration option in the .rainierrc file.
 */
declare module 'css-global-import' {
  const result: any;
  export default result;
}
