import { StoreMap } from '../rainier-store/types';

/**
 * This function will be generated by webpack during the build phase. The generated
 * function will instantiate an instance of each host app store defined in the host
 * application. The stores are retrieved based on the value of the "storesDir" config
 * in the .rainierrc file.
 *
 * @param serializedStores the JSON-serialized fields in each store. During the SSR,
 * the data in the stores must be serialized, passed to the browser, and then used to
 * rehydrate the stores on the client.
 */
export declare function initCustomClientStores(serializedStores: StoreMap): StoreMap;
