version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - install:
        run: npm ci
      - build:
        run: npm run build
      - test:
        run: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
