version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  'Build and Test':
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test

  'Eslint and Prettier':
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: prettier and eslint
          command: npm run code-checks
workflows:
  'Build and Test':
    jobs:
      - 'Build and Test'
  'Eslint and Prettier':
    jobs:
      - 'Eslint and Prettier'
