import { FunctionComponent } from 'react';
import { Stores } from '../rainier-store/types';

/**
 * This component is generated by webpack at build time. For each application store
 * that the host app defines, and for each platform store, a corresponding provider
 * will be used to make that store's state available to any component in the react
 * tree. Since this component sits at the very top of the react tree, ALL components
 * in the application will be able to use the provided stores.
 *
 * This component does a lot more, but that will all be documented in the wiki for the
 * rainier project.
 *
 * @param props contains the store instances that will be used to
 * create corresponding providers.
 */
declare const StoreProviders: FunctionComponent<{ stores: Stores }>;
