/**
 * The function will be generated by webpack at build time. The generated file
 * will contain the code that initializes each application controller defined
 * in the host app. Controllers from the host app are retrieved via the
 * "controllersDir" configuration option in the .rainierrc file.
 */
export declare function initControllers(): void;
