import { StoreMap } from '../rainier-store/types';

/**
 * This function will be generated by webpack during the build phase. The generated
 * function will instantiate an instance of each store defined in the host application.
 * The stores are retrieved based on the value of the "storesDir" config in the
 * .rainierrc file.
 *
 * By default, all server stores are initialized with an empty object.
 */
export declare function initCustomServerStores(): StoreMap;
